### ISSUE TITLE
Подсчет общего количества лайков.

### ISSUE THREAD

**Issue by rfhfnftd** [vladtsf/social-buttons#7]
Как посчитать и вывести общее количество лайков со всех соц. сетей?

**Comment by vladtsf** [comment]
Как-то так [https://gist.github.com/vtsvang/1381607](https://gist.github.com/vtsvang/1381607)

**Comment by rfhfnftd** [comment]
Спасибо большое, но это только для одного элемента с id, а если их много и они с классами?
P.S. Отличный плагин)

**Comment by vladtsf** [comment]
Тогда стоит сделать что-то вроде этого [https://gist.github.com/vtsvang/98497d3843598a489922](https://gist.github.com/vtsvang/98497d3843598a489922)

**Comment by rfhfnftd** [comment]
Работает, но при перезагрузке страницы не правильно считает либо считает только первый элемент.

**Comment by vladtsf** [comment]
Думаю стоит переработать скрипт в соответствии с вашей задачей.

**Comment by rfhfnftd** [comment]
В каком направление копать?))
